GET http://localhost:8000/api/games/9/gamers

###

POST http://localhost:8000/api/games/9/join
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NjE0NzEzNjMsImV4cCI6MTc5MzAwNzM2Mywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoic2F2dmEifQ.uiMpB7uvpyVKCr0WKAhH64hwrgutGijqWj-Vig7FWN3PWvuk_8fEKb2DujBbRcjZ_wIz_yLZLtb0NIibZuIUCkgkqjyr8rqMBJj6LSCVOZuuSKvUWfBrxP9ZDvbAvgRgILfr4w0GDMFqB_g9QFOYMsCn--G1CY_woK7njiY3a5gOdvvRvjiPuteqagoabac9ZRMXZOkxu2uWOP7WLXoDtbXWLdZpSQdpYWryqAt44uJ-Y0IKFUcOf16LFtTUPeeeauB5zfLWysTJwlTB5gfzOErPPWPIOTuE1w3aiTzRYpF9jYj9f1n9fBSTwJOluxadpPi_gUIMA4jCyiPpvuqQvw

###

POST http://localhost:8000/api/games/9/day